[build-system]
requires = ["scikit-build-core>=0.7", "pybind11>=2.10"]
build-backend = "scikit_build_core.build"

[project]
name = "deltaEGO_VDB"
version = "0.0.1"

[tool.scikit-build.wheel]
packages = ["src/deltaEGO_VDB"]